language: clojure

lein: 2.7.1

cache:
    directories:
        - geckodriver
        - joker

jdk:
    - oraclejdk8

addons:
    firefox: latest

env:
  JOKER_VERSION: '0.9.4'
  GECKODRIVER_VERSION: '0.19.1'

before_install:
    # geckodriver
    - |
        export PATH=$PWD/geckodriver:$PATH
        if !  type geckodriver > /dev/null 2>&1 || ! geckodriver --version | grep "${GECKODRIVER_VERSION}"; then
            rm -rf geckodriver
            mkdir geckodriver
            wget https://github.com/mozilla/geckodriver/releases/download/v${GECKODRIVER_VERSION}/geckodriver-v${GECKODRIVER_VERSION}-linux64.tar.gz -O geckodriver/geckodriver.tar.gz
            tar -xvf geckodriver/geckodriver.tar.gz -C geckodriver
            rm geckodriver/geckodriver.tar.gz
        fi
        geckodriver --version

    # joker
    - |
        export PATH=$PWD/joker:$PATH
        if ! type joker > /dev/null 2>&1 || ! joker --version | grep "${JOKER_VERSION}"; then
            rm -rf joker
            mkdir joker
            wget https://github.com/candid82/joker/releases/download/v${JOKER_VERSION}/joker-${JOKER_VERSION}-linux-amd64.zip -O joker/joker.zip
            unzip joker/joker.zip -d joker
            rm joker/joker.zip
        fi
        joker --version

    - cd frontend/

before_script:
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
    - npm install -g yarn
    - yarn install
    - 'npm install -g http-server'
    - 'http-server resources/public/ -p 3449 2>&1 | tee http-server.log &'

    - 'lein with-profile prod cljsbuild once min 2>&1 | tee cljsbuild.log'
    - 'lein less once'

script:
    - lein cljfmt check
    - 'find src/ \( -name "*.cljs" -or -name "*.clj" \) -print0 | xargs -0i --no-run-if-empty joker --lint {} 2>&1 | tee joker.out && [[ ! -s ./joker.out ]]'
    - alias firefox-bin='firefox'
    - lein doo firefox test once
    - lein test
    # check that there are no errors in http server after running selenium tests (like 404 on styles...)
    # also ignore missing favicon
    - "! grep --perl-regexp '^((?!favicon.ico).)*Error' http-server.log"

after_success:
    - cd ../
    - bin/deploy

