language: clojure

lein: 2.7.1

cache:
    directories:
        - geckodriver

jdk:
    - oraclejdk8

addons:
    firefox: latest

before_install:
    # geckodriver
    - |
        export PATH=$PWD/geckodriver:$PATH
        if ! type geckodriver > /dev/null 2>&1 || ! geckodriver --version | grep '0.18.0'; then
            rm -rf geckodriver
            mkdir geckodriver
            wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz -O geckodriver/geckodriver.tar.gz
            tar -xvf geckodriver/geckodriver.tar.gz -C geckodriver
            rm geckodriver/geckodriver.tar.gz
        fi
        geckodriver --version

    - cd frontend/

before_script:
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
    - npm install -g yarn
    - yarn install
    - lein git-deps
    - 'npm install -g http-server'
    - 'http-server resources/public/ -p 3449 2>&1 | tee http-server.log &'

    - 'lein with-profile prod cljsbuild once min 2>&1 | tee cljsbuild.log'
    - 'lein less once'

script:
    - lein cljfmt check
    - alias firefox-bin='firefox'
    - lein cljsbuild test
    - 'SELENIUM_BROWSER=firefox lein test'
    # check that there are no errors in http server after running selenium tests (like 404 on styles...)
    # also ignore missing favicon
    - "! grep --perl-regexp '^((?!favicon.ico).)*Error' http-server.log"

after_success:
    - cd ../
    - bin/deploy

