language: clojure

before_install:
    - npm install -g bower

install:
    - lein bower install

before_script:
    - npm install -g http-server

    - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
    - tar -xjf phantomjs-2.0.0-ubuntu-12.04.tar.bz2
    - sudo rm -rf /usr/local/phantomjs/bin/phantomjs
    - sudo mv phantomjs /usr/local/phantomjs/bin/phantomjs

    - http-server resources/public/ -p 3449 &

