language: clojure

cache:
    directories:
        - travis_phantomjs
        - geckodriver

jdk:
    - oraclejdk8

addons:
    firefox: latest

before_install:
    # phantomjs
    - 'phantomjs --version'
    - 'export PATH=$PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH'
    - 'phantomjs --version'
    - "if [ $(phantomjs --version) != '2.1.1' ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
    - "if [ $(phantomjs --version) != '2.1.1' ]; then wget https://assets.membergetmember.co/software/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2; fi"
    - "if [ $(phantomjs --version) != '2.1.1' ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
    - 'phantomjs --version'

    # geckodriver
    - |
        export PATH=$PWD/geckodriver:$PATH
        if ! type geckodriver > /dev/null 2>&1; then
            rm -rf geckodriver
            mkdir geckodriver
            wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz -O geckodriver/geckodriver.tar.gz
            tar -xvf geckodriver/geckodriver.tar.gz -C geckodriver
            mv geckodriver/geckodriver geckodriver/real-geckodriver
            rm geckodriver/geckodriver.tar.gz
            printf '#!/usr/bin/env bash

            args=("$@")

            # remove --binary or -b option
            for i in "${!args[@]}"; do
                if [[ "${args[$i]}" =~ ^(--binary|-b)(=.*)?$ ]]; then
                    unset args[$i]
                    if [[ ! "${args[$(($i + 1))]}" =~ ^- ]]; then
                        unset args[$(($i + 1))]
                    fi
                fi
            done

            args+=("--binary")
            args+=("$(which firefox)")

            real-geckodriver "${args[@]}"
            ' > geckodriver/geckodriver
            chmod +x geckodriver/geckodriver;
        fi
        geckodriver --version

    - 'npm install -g bower'

install:
    - 'lein bower install'

before_script:
    - 'export DISPLAY=:99.0'
    - 'sh -e /etc/init.d/xvfb start'
    - 'npm install -g http-server'
    - 'http-server resources/public/ -p 3449 2>&1 | tee http-server.log &'

    - 'lein cljsbuild once min 2>&1 | tee cljsbuild.log'
    - 'lein less once'

script:
    - lein cljsbuild test
    - 'SELENIUM_BROWSER=phantomjs lein test'
    - 'SELENIUM_BROWSER=firefox lein test'
    # check that there are no errors in http server after running selenium tests (like 404 on styles...)
    # also ignore missing favicon
    - "! grep --perl-regexp '^((?!favicon.ico).)*Error' http-server.log"
    # check that there are no errors or warnings in clojurescript compilation
    # also ignore redefining uuid by cognitect warning
    - "! grep --perl-regexp '(ERROR|WARNING((?!cognitect.transit/uuid).)*)$' cljsbuild.log"

after_success:
    - bin/deploy

