version: '2'
services:
    orientdb:
        image: orientdb/orientdb
        environment:
            ORIENTDB_ROOT_PASSWORD: root
        ports:
            - "2424:2424"
            - "2480:2480"
    backend:
        image: nenadalm/warehouse
        network_mode: host
        volumes:
            - .:/tmp/src
        security_opt:
            - label:disable
        command: sh -c 'lein deps && lein ring server-headless'
        ports:
            - "3000:3000"

