version: '2'
services:
    orientdb:
        image: orientdb/orientdb
        environment:
            ORIENTDB_ROOT_PASSWORD: root
        ports:
            - "2424:2424"
            - "2480:2480"
    backend:
        build:
            context: .
            dockerfile: dockerfiles/Clojure
        network_mode: host
        volumes:
            - .:/usr/src/app
        security_opt:
            - label:disable
        working_dir: /usr/src/app
        command: sh -c 'lein deps && lein ring server-headless'
        ports:
            - "3000:3000"

